Учебный проект: консольные забавы
htmlacademy-nodejs/560773-buy-and-sell-3 pull request #2
Opened 2020-12-26 08:50 UTC by NastyaKuvi

2020-12-26 11:45 UTC, Krabaton requested changes

2020-12-26 11:45 UTC, Krabaton commented on package.json
> +    "start-chrome": "node --inspect-brk ./src/service/service.js"
Почему --inspect-brk?

2020-12-26 11:45 UTC, Krabaton commented on src/service/cli/generate.js
> +      error(`Не больше 1000 объявлений`);
error(`Не больше ${MAX_COUNT} объявлений`);

2020-12-26 11:45 UTC, Krabaton commented on src/service/utils.js
> +  for (let i = someArray.length - 1; i > 0; i--) {
Больше for богу for's ...
```
function shuffle(array) {
  array.sort(() => Math.random() - 0.5);
}
```

2020-12-28 15:44 UTC, NastyaKuvi commented on src/service/cli/generate.js
> +      error(`Не больше 1000 объявлений`);
OK

2020-12-28 15:51 UTC, NastyaKuvi commented on src/service/utils.js
> +  for (let i = someArray.length - 1; i > 0; i--) {
ну что я могу сказать - вижу код в учебнике, пальцы сами ctrl+ C, ctrl + V на такие методы. Исправила.

2020-12-28 16:05 UTC, NastyaKuvi commented on package.json
> +    "start-chrome": "node --inspect-brk ./src/service/service.js"
в одной из глав про способы отладки был вариант в хроме запускать и для этого как раз нужен --inspect-brk, решила добавить команду, не знаю будет ли полезно в будущем, но когда что-то где-то не работает в хроме роднее как то

2020-12-28 22:19 UTC, Krabaton commented on package.json
> +    "start-chrome": "node --inspect-brk ./src/service/service.js"
ну меня больше интересовал суффикс  -brk. Прочитал он подавляет вывод. Чаще просто пишут --inspect

2020-12-28 22:20 UTC, merged